file_format: "1"
id: avocado
name: Avocado
type: shield
url: https://github.com/Narkoleptika/josukey/
requires: [seeed_xiao]
features:
    - keys
    - encoder
siblings:
    - avocado_left
    - avocado_right
